### ISSUE TITLE
Limit checked out items to 200 per patron

### ISSUE THREAD

**Issue by joshuago78** [gri-is/selfcheck#43]
From head of circulation:

> What we just found out with the new self check by Alma is that if a patron is above their maximum number and they try to self check out a book, it looks like they succeeded but they didn’t.
The receipt in the attachment prints out but it has no information and the item is not actually charged out on Alma.  It is blocking the patron except Alma is not telling them that they are blocked or that
their self check out did not work so they think that they have successfully charged out a book when they haven’t.  Then they walk away with the book and it’s now missing.

- [x] check for limit maximum error
- [x] if limit reached: present message to user, do not print out the slip

**Comment by lolliffe** [comment]
Response return doesn't show number of books.  It appears to simply get back from Alma that no items are available for checkout.  `{'total_record_count': 0}`

Waiting for a working patron example from Jay, to confirm this.

**Comment by joshuago78** [comment]
closed with #44
